on:
  push:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to aws 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::601394826940:role/test-ecr-cache-gha
          role-session-name: gha
          aws-region: us-west-2
      - name: qemu
        uses: docker/setup-qemu-action@v2
        with: 
          platforms: arm64
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 601394826940.dkr.ecr.us-west-2.amazonaws.com/test-ecr
          cache-from: type=registry,ref=601394826940.dkr.ecr.us-west-2.amazonaws.com/test-ecr
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
